### ISSUE TITLE
warning: the 'gets' function is dangerous and should not be used.

### ISSUE THREAD

**Issue by aganm** [fredericojordan/fast-chess#11]
gcc gives me 2 warnings about 'gets':

`fast-chess.c:2779:2: warning: implicit declaration of function 'gets'; did you mean 'fgets'? [-Wimplicit-function-declaration]`

and

`fast-chess.c:2779: warning: the 'gets' function is dangerous and should not be used.`

**Comment by aganm** [comment]
Fixed it ;p 
Just need to replace the line 2779
`gets( input );`
by
`fgets( input, 100, stdin);`

**Comment by aganm** [comment]
I'm a bit lazy to create a fork just for that, could you commit that in please? Thanks!

**Comment by fredericojordan** [comment]
Hello, thanks for your interest!
This has been fixed with #15 
Have a nice day!
